In [2]:
from numpy import *
eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
import numpy as np
n1 = np.array([1, 2, 3])
n1

array([1, 2, 3])

In [20]:
import numpy as np
n3 = np.array([[1, 2], [3, 4]])
n3

array([[1, 2],
       [3, 4]])

In [26]:
list = [1, 2, 3], [2, 3, 4]
n1 = np.array(list, dtype = float)
print(n1)
print(n1.dtype)
print(type(n1[0]))

[[1. 2. 3.]
 [2. 3. 4.]]
float64
<class 'numpy.ndarray'>


In [27]:
n1 = np.array([1, 2, 3])
n2 = np.array(n1, copy = True)
n2[0] = 3
n2[2] = 1
print(n1)
print(n2)

[1 2 3]
[3 2 1]


In [29]:
nd1 = [1, 2, 3]
nd2 = np.array(nd1, ndmin = 5)
nd2

array([[[[[1, 2, 3]]]]])

In [30]:
n = np.empty([2, 3])
n

array([[1., 2., 3.],
       [2., 3., 4.]])

In [41]:
n = np.zeros(3)
n

array([0., 0., 0.])

In [43]:
n = np.ones(3)
n

array([1., 1., 1.])

In [45]:
n = np.full((3, 3), 8)
n

array([[8, 8, 8],
       [8, 8, 8],
       [8, 8, 8]])

In [46]:
n = np.arange(1, 12, 2)
n

array([ 1,  3,  5,  7,  9, 11])

In [49]:
n1 = np.linspace(7500, 10000, 6, retstep = True)
n1

(array([ 7500.,  8000.,  8500.,  9000.,  9500., 10000.]), 500.0)

In [52]:
n = np.logspace(0, 63, 64, base = 2, dtype = 'int')
n

array([                   1,                    2,                    4,
                          8,                   16,                   32,
                         64,                  128,                  256,
                        512,                 1024,                 2048,
                       4096,                 8192,                16384,
                      32768,                65536,               131072,
                     262144,               524288,              1048576,
                    2097152,              4194304,              8388608,
                   16777216,             33554432,             67108864,
                  134217728,            268435456,            536870912,
                 1073741824,           2147483648,           4294967296,
                 8589934592,          17179869184,          34359738368,
                68719476736,         137438953472,         274877906944,
               549755813888,        1099511627776, 

In [58]:
# 随机数
n = np.random.randn(5,2)
n

array([[0.08526413, 0.10803059],
       [0.40179144, 0.91106092],
       [0.3797685 , 0.01345055],
       [0.38599883, 0.90720367],
       [0.96620739, 0.37338488]])

In [59]:
# 满足正态分布的随机数
n = np.random.randn(5,2)
n

array([[ 0.28029304, -1.61543483],
       [ 0.39740214, -1.37180622],
       [ 0.3538272 ,  1.85393392],
       [-1.19476951,  0.7185234 ],
       [ 0.52221388,  0.12091057]])

In [61]:
n1 = np.random.randint(1, 3, 10)
n1

array([2, 1, 2, 2, 1, 1, 1, 2, 1, 2])

In [63]:
n2 = np.random.randint(5, 10)
n2

9

In [64]:
n2 = np.random.randint(5, size = (2, 5))

In [65]:
n2

array([[4, 4, 2, 1, 1],
       [3, 2, 1, 2, 3]])

In [67]:
n = np.random.normal(0, 0.1, 10)
n

array([-0.03545908, -0.00983161, -0.01818504,  0.01527221, -0.07054798,
       -0.07789548, -0.06192609,  0.08364234,  0.00507258,  0.19092335])

In [69]:
n1 = np.asarray([1, 2, 3])
n2 = np.asarray([(1, 1), (2, 3)])
n3 = np.asarray((1, 2, 3))
n4 = np.asarray(((1, 1), (1, 2), (1, 3)))
n5 = np.asarray(([1, 1], [1, 2]))
print(n1)
print(n2)
print(n3)
print(n4)
print(n5)

[1 2 3]
[[1 1]
 [2 3]]
[1 2 3]
[[1 1]
 [1 2]
 [1 3]]
[[1 1]
 [1 2]]


In [70]:
n = np.frombuffer(b'mingrisoft', dtype = 'S1')
n

array([b'm', b'i', b'n', b'g', b'r', b'i', b's', b'o', b'f', b't'],
      dtype='|S1')

In [71]:
iterable = (x * 2 for x in range(5))
n = np.fromiter(iterable, dtype = 'int')
n

array([0, 2, 4, 6, 8])

In [72]:
n = np.empty_like([[1, 2], [3, 4]])
n

array([[3458764513820540928, 3458764513820540928],
       [                  4,                   0]])

In [74]:
n6 = np.empty_like([[1, 2], [3, 4]])
n6

array([[3458764513820540928, 2305851780210574927],
       [3458764513820540930,     571720950304424]])

In [76]:
n = np.ones_like([[0.1, 0.2, 0.3], [0.4, 0.5, 0.6]])
n

array([[1., 1., 1.],
       [1., 1., 1.]])

In [77]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [79]:
n1 = np.full_like(a, 1)
n2 = np.full_like(a, 0.2)
n3 = np.full_like(a, 0.2, dtype = 'float')
print(n1)
print(n2)
print(n3
     )

[1 1 1 1 1 1]
[0 0 0 0 0 0]
[0.2 0.2 0.2 0.2 0.2 0.2]


In [81]:
n1 = np.array([1, 2])
n2 = np.array([3, 4])
print(n1 >= n2)
print(n1 == n2)
print(n1 <= n2)
print(n1 != n2)

[False False]
[False False]
[ True  True]
[ True  True]


In [82]:
n1 = np.linspace(7500, 10000, 6, dtype = 'int')
print(n1)
print(n1/1000)

[ 7500  8000  8500  9000  9500 10000]
[ 7.5  8.   8.5  9.   9.5 10. ]


In [83]:
n1 = np.array([1, 2, 3])
print(n1[0])
print(n1[1:])
print(n1[:2])

1
[2 3]
[1 2]


In [84]:
n = np.arange(20)
print(n[::2])
print(n[1::5])

[ 0  2  4  6  8 10 12 14 16 18]
[ 1  6 11 16]


In [85]:
print(n[::-1])

[19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


In [86]:
print(n[:-3:-1])

[19 18]


In [90]:
print(n[-3:-5:-1])

[17 16]


In [88]:
print(n[-5::-1])

[15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


In [103]:
n = np.arange(10)
print(n)
print(n[:3])
print(n[6:])
print(n[::])
print(n[:])
print(n[::2])
print(n[1::5])
print(n[2::6])
# 倒序
print(n[-3:])
print(n[-3::])
print(n[:-3])
print(n[::-1])
print('---------------------')
print('从最后一个到-6且步长为-3')
print(n[:-6:-3])
print('从最后一个到-3且步长为-1')
print('print(\'n[-1:-3:-1]\')的-1可以省略')
print(n[:-3:-1])
print('从最后一个到-3且步长为1')
print(n[:-3:1])
print('从-3至-5且步长为-1')
print(n[-3:-5:-1])
print('从-5至0且步长为-1')
print(n[-5::-1])

[0 1 2 3 4 5 6 7 8 9]
[0 1 2]
[6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[1 6]
[2 8]
[7 8 9]
[7 8 9]
[0 1 2 3 4 5 6]
[9 8 7 6 5 4 3 2 1 0]
---------------------
从最后一个到-6且步长为-3
[9 6]
从最后一个到-3且步长为-1
print('n[-1:-3:-1]')的-1可以省略
[9 8]
从最后一个到-3且步长为1
[0 1 2 3 4 5 6]
从-3至-5且步长为-1
[7 6]
从-5至0且步长为-1
[5 4 3 2 1 0]


In [104]:
n = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(n)
print(n[:2, 1:])
print(n[1, :2])
print(n[:2, :2])
print(n[:, :1])
print(n[:, -1:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 3]
 [5 6]]
[4 5]
[[1 2]
 [4 5]]
[[1]
 [4]
 [7]]
[[3]
 [6]
 [9]]


In [105]:
n = np.arange(6)
print(n)
n1 = n.reshape(2, 3)
n1

[0 1 2 3 4 5]


array([[0, 1, 2],
       [3, 4, 5]])

In [106]:
n = np.array([[0, 1, 2], [3, 4, 5]])
n1 = n.reshape(3, 2)
n1

array([[0, 1],
       [2, 3],
       [4, 5]])

In [108]:
n = np.arange(24).reshape(4, 6)
n.T

array([[ 0,  6, 12, 18],
       [ 1,  7, 13, 19],
       [ 2,  8, 14, 20],
       [ 3,  9, 15, 21],
       [ 4, 10, 16, 22],
       [ 5, 11, 17, 23]])

In [114]:
n = np.array([['A', 100], ['B', 200], ['C', 300], ['D', 400]])
n.transpose()

array([['A', 'B', 'C', 'D'],
       ['100', '200', '300', '400']], dtype='<U3')

In [115]:
n1 = np.array([[1, 2], [3, 4], [5, 6]])
n2 = np.array([[10, 20], [30, 40], [50, 60]])

In [117]:
np.hstack((n1, n2))

array([[ 1,  2, 10, 20],
       [ 3,  4, 30, 40],
       [ 5,  6, 50, 60]])

In [118]:
np.vstack((n1, n2))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [10, 20],
       [30, 40],
       [50, 60]])

In [119]:
n2 = np.delete(n1, 2, axis = 0)
n2

array([[1, 2],
       [3, 4]])

In [121]:
n3 = np.delete(n1, 0, axis = 1)
n3

array([[2],
       [4],
       [6]])

In [128]:
n4 = np.delete(n1, (0,2), 0)
n4

array([[3, 4]])

In [129]:
np.where(n1 > 5, True, False)

array([[False, False],
       [False, False],
       [False,  True]])

In [133]:
n5 = np.hstack((n1, n2))

In [134]:
np.where(n5 > 5, True, False)

array([[False, False, False],
       [False, False, False],
       [False,  True,  True]])